### ISSUE TITLE
list:users YAML output and token_auth option

### ISSUE THREAD

**Issue by chriscroome** [nodeone/userconsole#2]
Perhaps it would be nice if `list:users` could output in formats other than text, for example:

```yaml
---
users:
  foo:
    email: foo@example.org
    superuser_access: true
  bar:
    email: bar@example.org
    superuser_access: false
```

It would also be good to have an option to output the `token_auth` &mdash; this is needed when doing something like automating the adding of Matomo tracking to a WordPress site using the WP-Piwik plugin.
